### PR TITLE
T/47

### LINKED ISSUE #47: Initialize data via setData() doesn't work properly
`editor.setData()` or `editor.data.set()` in real-time collaboration works incorrect. Using it may overwrite local changes on remote clients.

### PR DESCRIPTION
**Pull request by elszczepano**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Changed the way of data initialization. Instead of using `setData()`, the content is set via `innerHTML`. Closes #47.

---

### CODE REVIEW

File: tests/ckeditor.js [hunk 1]
```diff
@@ -104,19 +104,6 @@ describe( 'CKEditor Component', () => {
 				expect( vm.value ).to.equal( '' );
 			} );
 
-			it( 'should set the initial data', done => {
```
Comment (pomek) [inline tests/ckeditor.js]: This test should not be removed. We need to be sure that the specified data has been passed to the editor.

File: src/ckeditor.js [hunk 2]
```diff
@@ -9,7 +9,11 @@ export default {
 	name: 'ckeditor',
 
 	render( createElement ) {
-		return createElement( this.tagName );
+		return createElement(this.tagName, {
```
Comment (oleq) [inline src/ckeditor.js]: Code style.

File: tests/ckeditor.js [hunk 3]
```diff
@@ -104,14 +104,15 @@ describe( 'CKEditor Component', () => {
...
-				const setDataStub = sandbox.stub( MockEditor.prototype, 'setData' );
-				const { wrapper } = createComponent( {
+			it( 'should set the initial data by using innerHTML, not by "setData()"', done => {
```
Comment (oleq) [inline tests/ckeditor.js]: Missing link to the issue.

File: tests/ckeditor.js [hunk 4]
```diff
@@ -104,14 +104,15 @@ describe( 'CKEditor Component', () => {
...
+				const { wrapper, vm } = createComponent( {
 					value: 'foo'
 				} );
 
 				Vue.nextTick( () => {
-					sinon.assert.calledWithExactly( setDataStub, 'foo' );
+
+					expect( vm.$el.innerHTML ).to.equal( 'foo' );
+					expect( vm.instance.setDataCounter).to.equal(0);
```
Comment (oleq) [inline tests/ckeditor.js]: Code style (twice).

File: src/ckeditor.js [hunk 5]
```diff
@@ -9,7 +9,11 @@ export default {
...
+			domProps: {
+				innerHTML: this.value || ''
```
Comment (oleq) [inline src/ckeditor.js]: Does this work when `tagName` is `textarea`?

File: tests/ckeditor.js (hunk 4 above)
Comment (oleq) [inline tests/ckeditor.js]: Also: use `sinon.spy( vm.instance, 'setData' )` and `sinon.assert.notCalled( spy )` instead of the counter. Don't spread the logic across the files when it's unnecessary.

Comment (pjasiun) [reply tests/ckeditor.js]: `sinon.spy( vm.instance, 'setData' )` was problematic in this case. You can not do it before `Vue.nextTick`, because `vm.instance` was `null`, and you can not do it after `Vue.nextTick` because the editor is already initialized then. Also, note that this counter does not change the logic of the `EditorMock`, it just keep additional information.

File: src/ckeditor.js (hunk 5 above)
Comment (oleq) [reply src/ckeditor.js]: I'm worried because setting the value of an input like this works only once (the second one will be ignored). In theory, we do it only once but still, this is not the right way IMO.

Comment (oleq) [reply src/ckeditor.js]: Also... does this whole `innerHTML` thing work when a content with/without entities is passed as a value?

Comment (elszczepano) [reply src/ckeditor.js]: I've built a sample with `tagName` set to `textarea`. The editor seems to work properly, no error occurs on init and on destroy.
